### ISSUE TITLE
ApiServiceClass includes the query params twice

### ISSUE THREAD

**Issue by nguyen-le** [siosphere/beefjs#5]
When building a GET request and passing in data = `{page: 0, limit: 10}`, the following query string is formed (or should i say malformed 😆 ): 
`?page=0&limit=10&%7b%2522page%2522:0,%2522limit%2522:10%7d`
``` js
return $.ajax({
    url: this._buildUrl(url, data),
>>  data: JSON.stringify(data),  <<
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    method: "GET",
    dataType: 'json'
});
```

**Comment by siosphere** [comment]
This has been fixed in v0.9.3 https://github.com/siosphere/beefjs/releases/tag/0.9.3
